export const styles = {
    "video-container": "player_video-container__I9fU2",
    "video-wrapper": "player_video-wrapper__tN3j3",
    "video-controls": "toolbar_video-controls__wzQC1",
    "video-controls-hidden": "toolbar_video-controls-hidden__PscSU",
    "video-progress": "progress_video-progress__DMF70",
    "video-pretime": "progress_video-pretime__gDMzS",
    "video-buffered": "progress_video-buffered__xlu1O",
    "video-completed": "progress_video-completed__j0yvy",
    "video-dot": "progress_video-dot__u2nX7",
    "video-dot-hidden": "progress_video-dot-hidden__S-oLG",
    "video-play": "controller_video-play__aWE0Y",
    "video-subplay": "controller_video-subplay__ywUzK",
    "video-start-pause": "controller_video-start-pause__JnB3x",
    "video-duration": "controller_video-duration__8upHt",
    "video-duration-completed": "controller_video-duration-completed__PYm69",
    "video-settings": "controller_video-settings__SiNyl",
    "video-subsettings": "controller_video-subsettings__6Jtl7",

    "video-playrate-set": "controller_video-playrate-set__VwnVz",
    "video-resolvepower-set": "controller_video-resolvepower-set__JqEYD",
    "video-volume": "controller_video-volume__R8ory",
    "video-volume-progress": "controller_video-voulme-progress__VyO8-",
    "video-volume-completed": "controller_video-volume-completed__zwRNX",
    "video-volume-dot": "controller_video-volume-dot__5dlAl",
    "video-fullscreen": "controller_video-fullscreen__ZLYIr",
    "video-duration-all": "controller_video-duration-all__gGLip",

    "video-controller": "controller_video-controller__SO9PL",
    "video-playrate": "controller_video-playrate__lj-mz",
    "video-resolvepower": "controller_video-resolvepower__OuokG",

    "video-volume-set": "controller_video-volume-set__wurEP",
    "video-volume-show": "controller_video-volume-show__bb2Jm",

    "loading-mask": "",
    "loading-container": "",
    "loading-item": "",
    "loading-title": "",
    "error-mask": "",
    "error-container": "",
    "error-item": "",
    "error-title": "",

}